import React from 'react';
import { ExternalLink, Plus, RotateCcw, Trash2 } from 'lucide-react';
import { ROUTINE_DAYS } from '../utils/routineValidationUtils.js';

const fieldClass = 'w-full min-h-10 px-2.5 py-2 text-xs bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg';

export const ExtractedRoutineReview = ({ rows, onUpdate, onDelete, onAdd, onReset, previewUrl }) => (
  <section className="space-y-3">
    <div className="flex items-center justify-between gap-2"><div><h4 className="text-sm font-extrabold text-slate-900 dark:text-white">Routine rows</h4><p className="text-[11px] text-slate-500 dark:text-slate-400">Unclear groups are excluded until you resolve and include them.</p></div><button type="button" onClick={onAdd} className="min-h-10 inline-flex items-center gap-1.5 px-3 text-xs font-bold bg-slate-900 dark:bg-slate-700 text-white rounded-xl"><Plus className="w-3.5 h-3.5" />Add missing row</button></div>
    <div className="space-y-3">{rows.map(row => <div key={row.tempId} className={`p-3 rounded-2xl border ${row.validation.errors.length ? 'border-rose-300 dark:border-rose-800' : row.validation.warnings.length || row.conflicts.length ? 'border-amber-300 dark:border-amber-800' : 'border-slate-200 dark:border-slate-700'} bg-slate-50 dark:bg-slate-800/50`}>
      <div className="flex flex-wrap items-center justify-between gap-2 mb-3"><label className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-200"><input type="checkbox" checked={row.include !== false} onChange={event => onUpdate(row.tempId, 'include', event.target.checked)} />Include row</label><div className="flex items-center gap-2"><span className="text-[10px] font-bold text-slate-400">Page {row.sourcePage} · {Math.round(row.confidence * 100)}%</span>{previewUrl && <button type="button" onClick={() => window.open(`${previewUrl}${previewUrl.includes('#') ? '&' : '#'}page=${row.sourcePage}`, '_blank', 'noopener,noreferrer')} className="inline-flex items-center gap-1 text-[10px] font-bold text-cyan-600 dark:text-cyan-400"><ExternalLink className="w-3 h-3" />View source</button>}</div></div>
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-2">
        <div><label className="text-[10px] font-bold text-slate-500">Day</label><select aria-label={`Day for ${row.courseId || 'routine row'}`} value={row.dayOfWeek} onChange={event => onUpdate(row.tempId, 'dayOfWeek', event.target.value)} className={fieldClass}>{ROUTINE_DAYS.map(day => <option key={day}>{day}</option>)}</select></div>
        <div><label className="text-[10px] font-bold text-slate-500">Start</label><input aria-label={`Start time for ${row.courseId || 'routine row'}`} type="time" value={row.startTime} onChange={event => onUpdate(row.tempId, 'startTime', event.target.value)} className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">End</label><input aria-label={`End time for ${row.courseId || 'routine row'}`} type="time" value={row.endTime} onChange={event => onUpdate(row.tempId, 'endTime', event.target.value)} className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">Course ID</label><input aria-label="Routine course ID" value={row.courseId} onChange={event => onUpdate(row.tempId, 'courseId', event.target.value)} className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">Group</label><input aria-label={`Group for ${row.courseId || 'routine row'}`} value={row.group} onChange={event => onUpdate(row.tempId, 'group', event.target.value)} placeholder="B2 / ALL" className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">Section</label><input aria-label={`Section for ${row.courseId || 'routine row'}`} value={row.section} onChange={event => onUpdate(row.tempId, 'section', event.target.value)} className={fieldClass} /></div>
        <div className="col-span-2"><label className="text-[10px] font-bold text-slate-500">Course title</label><input aria-label={`Course title for ${row.courseId || 'routine row'}`} value={row.courseTitle} onChange={event => onUpdate(row.tempId, 'courseTitle', event.target.value)} className={fieldClass} /></div>
        <div className="col-span-2"><label className="text-[10px] font-bold text-slate-500">Teacher</label><input aria-label={`Teacher for ${row.courseId || 'routine row'}`} value={row.teacherName} onChange={event => onUpdate(row.tempId, 'teacherName', event.target.value)} className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">Room</label><input aria-label={`Room for ${row.courseId || 'routine row'}`} value={row.room} onChange={event => onUpdate(row.tempId, 'room', event.target.value)} className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">Building</label><input aria-label={`Building for ${row.courseId || 'routine row'}`} value={row.building} onChange={event => onUpdate(row.tempId, 'building', event.target.value)} className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">Class type</label><select aria-label={`Class type for ${row.courseId || 'routine row'}`} value={row.classType} onChange={event => onUpdate(row.tempId, 'classType', event.target.value)} className={fieldClass}><option value="theory">Theory</option><option value="lab">Lab</option><option value="sessional">Sessional</option><option value="tutorial">Tutorial</option></select></div>
        <div><label className="text-[10px] font-bold text-slate-500">Credit</label><input aria-label={`Credit for ${row.courseId || 'routine row'}`} type="number" min="0" step="0.25" value={row.credit} onChange={event => onUpdate(row.tempId, 'credit', Number(event.target.value))} className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">Effective start</label><input aria-label={`Effective start for ${row.courseId || 'routine row'}`} type="date" value={row.effectiveStartDate || ''} onChange={event => onUpdate(row.tempId, 'effectiveStartDate', event.target.value)} className={fieldClass} /></div>
        <div><label className="text-[10px] font-bold text-slate-500">Effective end</label><input aria-label={`Effective end for ${row.courseId || 'routine row'}`} type="date" value={row.effectiveEndDate || ''} onChange={event => onUpdate(row.tempId, 'effectiveEndDate', event.target.value)} className={fieldClass} /></div>
      </div>
      <label className="mt-2 flex items-center gap-2 text-[11px] text-slate-600 dark:text-slate-300"><input type="checkbox" checked={Boolean(row.isCommon)} onChange={event => onUpdate(row.tempId, 'isCommon', event.target.checked)} />Common class for all groups/sections</label>
      {row.conflicts.map(conflict => <p key={`${row.tempId}-${conflict.type}`} className="mt-2 text-[11px] font-bold text-amber-700 dark:text-amber-300">{conflict.label}</p>)}
      {[...row.validation.errors, ...row.validation.warnings].map(message => <p key={message} className="mt-1 text-[11px] text-rose-600 dark:text-rose-400">{message}</p>)}
      <div className="flex flex-wrap justify-end gap-2 mt-3">{row._ocrOriginal && <button type="button" onClick={() => onReset(row.tempId)} className="min-h-9 inline-flex items-center gap-1 px-3 text-xs font-bold text-slate-600 dark:text-slate-300 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700"><RotateCcw className="w-3.5 h-3.5" />Reset OCR row</button>}<button type="button" onClick={() => onDelete(row.tempId)} className="min-h-9 inline-flex items-center gap-1 px-3 text-xs font-bold text-rose-600 dark:text-rose-400 rounded-lg hover:bg-rose-50 dark:hover:bg-rose-950/30"><Trash2 className="w-3.5 h-3.5" />Delete row</button></div>
    </div>)}</div>
  </section>
);
